"""Helper utilities to access the last result image generated by Fooocus."""

from __future__ import annotations

import os
from typing import Optional
from PIL import Image

import modules.private_logger as private_logger


def get_last_result_image() -> Optional[Image.Image]:
    """Return the last saved image as a :class:`PIL.Image.Image`.

    The asynchronous worker stores the path to the most recently saved image
    via :func:`modules.private_logger.log`. This helper loads that image if it
    exists.
    """
    path = private_logger.get_last_saved_image()
    if path and os.path.exists(path):
        try:
            return Image.open(path)
        except Exception:
            return None
    return None
